function dsp = dsprop_struct_template()
%
%-------function help------------------------------------------------------
% NAME
%   dsprop_struct_template.m
% PURPOSE
%   template to define the dsproperties for a data set or model output
% USAGE
%   dsp = dsprop_struct_template()
% OUTPUT
%   dsp - dsproperties struct array
% SEE ALSO
%   dsproperties and dstable.m
%
% Author: Ian Townend
% CoastalSEA (c)June 2020
%--------------------------------------------------------------------------
%
    dsp = struct('Variables',[],'Row',[],'Dimensions',[]);           
    dsp.Variables = struct(...   %cell arrays can be column or row vectors
        'Name',{'Var1','Var2','Var3'},...
        'Description',{'Variable 1','Variable 2','Variable 3'},...
        'Unit',{'u1','u2','u3'},...
        'Label',{'Label1','Label2','Label3'},...
        'QCflag',{'qc1','qc2','qc3'}); 
    dsp.Row = struct(...
        'Name',{'RowName'},...
        'Description',{'Row Description'},...
        'Unit',{'u'},...
        'Label',{'Row label'},...
        'Format',{'time format'});  %only used for datetime and duration formats     
    dsp.Dimensions = struct(...    
        'Name',{'Dim1';'Dim2'},...
        'Description',{'Distance 1';'Distance 2'},...
        'Unit',{'u1';'u2'},...
        'Label',{'Label1';'Label2'},...
        'Format',{'-';'-'});        %only used for datetime and duration formats
end